version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - web-analyzer

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:80"
    networks:
      - web-analyzer

networks:
  web-analyzer:
    driver: bridge
